global:
  scrape_interval: 30s     # Optimizado para no saturar la CPU
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'node'        # Cambiado de 'servidor' a 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'       # AÃ±adido (estaba faltando)
    static_configs:
      - targets: ['nginx-exporter:9113']
